services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  ms-identidad:
    build: ./services/ms-identidad
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: mongodb://mongo:27017/ms-identidad
      RABBITMQ_URI: amqp://rabbitmq:5672
      OPERATOR_ID: ${OPERATOR_ID:-}
      OPERATOR_NAME: ${OPERATOR_NAME:-Operador Ciudadano EAFIT}
      JWT_SECRET: ${JWT_SECRET:-cambiar-en-produccion}
    depends_on:
      - mongo
      - rabbitmq

volumes:
  mongo-data:
